// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateReport(arg1:main.ReportRequest):Promise<void>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;

export function SelectFiles():Promise<Array<string>>;
